CREATE TABLE o2o_area(
	id int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
	city_id int(11) UNSIGNED NOT NULL DEFAULT 0,
	name VARCHAR(20) NOT NULL DEFAULT '',
	parent_id INT(11) UNSIGNED NOT NULL DEFAULT 0,
	listorder int(8) UNSIGNED NOT NULL DEFAULT 0,
	status tinyint(1) NOT NULL DEFAULT 0,
	create_time int(11) UNSIGNED NOT NULL DEFAULT 0,
	update_taime INT(11) UNSIGNED NOT NULL DEFAULT 0,
	PRIMARY KEY(id),
	KEY city_id(city_id),
	KEY parent_id(parent_id)	
)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8;