CREATE TABLE o2o_bis_account(
	id int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
	username VARCHAR(20) NOT NULL DEFAULT '',
	password CHAR(32) NOT NULL DEFAULT '123456',
	code VARCHAR(10) NOT NULL DEFAULT '',
	bis_id INT(11) UNSIGNED NOT NULL DEFAULT 0,
	is_main tinyint(1) UNSIGNED NOT NULL DEFAULT 0,
	last_login_ip VARCHAR(20) NOT NULL DEFAULT '',
	last_login_time INT(11) NOT NULL DEFAULT 0,
	listorder int(8) UNSIGNED NOT NULL DEFAULT 0,
	status tinyint(1) NOT NULL DEFAULT 0,
	create_time int(11) UNSIGNED NOT NULL DEFAULT 0,
	update_taime INT(11) UNSIGNED NOT NULL DEFAULT 0,
	PRIMARY KEY(id),
	KEY bis_id(bis_id),
	KEY username(username)	
)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8;