CREATE TABLE o2o_deal(
	id int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
	name VARCHAR(20) NOT NULL DEFAULT '',
	bis_id INT(11) UNSIGNED NOT NULL DEFAULT 0,
	bis_account_id INT(11) UNSIGNED NOT NULL DEFAULT 0,
	location_id VARCHAR(20)  NOT NULL DEFAULT '',
	category_id INT(11) UNSIGNED NOT NULL DEFAULT 0,
	se_category_id VARCHAR(30)  NOT NULL DEFAULT '',
	image VARCHAR(255) NOT NULL DEFAULT '',
	description TEXT NOT NULL,
	notes TEXT NOT NULL,
	start_time VARCHAR(30)  NOT NULL DEFAULT '',
	end_time VARCHAR(30)  NOT NULL DEFAULT '',
	orgin_price DECIMAL(8,2) UNSIGNED NOT NULL DEFAULT 0.00,
	present_price DECIMAL(8,2) UNSIGNED NOT NULL DEFAULT 0.00,
	banlance_price DECIMAL(8,2) UNSIGNED NOT NULL DEFAULT 0.00,
	city_id INT(11) UNSIGNED NOT  NULL DEFAULT 0,
	buy_count INT(5) NOT NULL DEFAULT 0,
	total_count INT(7) NOT NULL DEFAULT 0,
	coupons_start_time VARCHAR(30)  NOT NULL DEFAULT '',
	coupons_end_time VARCHAR(30)  NOT NULL DEFAULT '',
	xpoint VARCHAR(20) NOT NULL DEFAULT '',
	ypoint VARCHAR(20) NOT NULL DEFAULT '',
	listorder int(8) UNSIGNED NOT NULL DEFAULT 0,
	status tinyint(1) NOT NULL DEFAULT 0,
	create_time int(11) UNSIGNED NOT NULL DEFAULT 0,
	update_time INT(11) UNSIGNED NOT NULL DEFAULT 0,
	PRIMARY KEY(id),
	KEY name(name),
	KEY category_id(category_id),
	KEY se_category_id(se_category_id),
	KEY city_id(city_id),
	KEY start_time(start_time),
	KEY end_time(end_time),
	KEY present_price(present_price)
)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8;