CREATE TABLE o2o_city(
	id int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
	uname VARCHAR(20) NOT NULL DEFAULT '',
	name VARCHAR(20) NOT NULL DEFAULT '',
	parent_id INT(11) UNSIGNED NOT NULL DEFAULT 0,
	listorder int(8) UNSIGNED NOT NULL DEFAULT 0,
	status tinyint(1) NOT NULL DEFAULT 0,
	create_time int(11) UNSIGNED NOT NULL DEFAULT 0,
	update_time INT(11) UNSIGNED NOT NULL DEFAULT 0,
	PRIMARY KEY(id),
	KEY name(name),
	KEY parent_id(parent_id)	
)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8;