CREATE TABLE o2o_featured(
	id int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
	deal_id INT(11) UNSIGNED NOT NULL DEFAULT 0,
	title VARCHAR(30) NOT NULL DEFAULT '',
	type tinyint(1) NOT NULL DEFAULT 0,
	image VARCHAR(255) NOT NULL DEFAULT '',
	name VARCHAR(20) NOT NULL DEFAULT '',
	url VARCHAR(255) NOT NULL DEFAULT '',
	listorder int(8) UNSIGNED NOT NULL DEFAULT 0,
	status tinyint(1) NOT NULL DEFAULT 0,
	create_time int(11) UNSIGNED NOT NULL DEFAULT 0,
	update_time INT(11) UNSIGNED NOT NULL DEFAULT 0,
	PRIMARY KEY(id)
)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8;