CREATE TABLE o2o_user(
	id int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
	username VARCHAR(20) NOT NULL DEFAULT '',
	password CHAR(32) NOT NULL DEFAULT '123456',
	code VARCHAR(10) NOT NULL DEFAULT '',
	email VARCHAR(20) NOT NULL DEFAULT '',
	last_login_ip VARCHAR(20) NOT NULL DEFAULT '',
	last_login_time INT(11) NOT NULL DEFAULT 0,
	listorder int(8) UNSIGNED NOT NULL DEFAULT 0,
	status tinyint(1) NOT NULL DEFAULT 0,
	create_time int(11) UNSIGNED NOT NULL DEFAULT 0,
	update_time INT(11) UNSIGNED NOT NULL DEFAULT 0,
	PRIMARY KEY(id),
	UNIQUE KEY(username),
	UNIQUE KEY(email)
)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8;