CREATE TABLE o2o_order(
	id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
	winxin_id VARCHAR(100) NOT NULL DEFAULT '',
	user_id INT(11) UNSIGNED NOT NULL DEFAULT 0,
	pay_time VARCHAR(20) UNSIGNED NOT NULL DEFAULT '',
	payment_id tinyint(1) NOT NULL DEFAULT 1,
	deal_id INT(11) UNSIGNED NOT NULL DEFAULT 0,
	deal_count INT(11) UNSIGNED NOT NULL DEFAULT 0,
	pay_status tinyint(1) NOT NULL DEFAULT 0,
	total_price DECIMAL(20,2) NOT NULL DEFAULT 0.00,
	weixin_total_price DECIMAL(20,2) NOT NULL DEFAULT 0.00,
	referer VARCHAR(255) NOT NULL DEFAULT '',
	status tinyint(1) NOT NULL DEFAULT 1,
	create_time INT(11) NOT NULL DEFAULT 0,
	update_time INT(11) NOT NULL DEFAULT 0,
	primary key(id)
)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;